### ISSUE TITLE
Can't get plugin to work

### ISSUE THREAD

**Issue by gaggle** [JamesPan/hexo-filter-asset-inline#1]
Hi @JamesPan,

I can't get the plugin working, nothing changes in the outputted HTML.

The plugin registers to the `after_render:html` filter event, and then assumes it can read files from the public folder. But when I debug the logic no files are actually written when the event runs, which means [all this logic never runs](https://github.com/JamesPan/hexo-filter-asset-inline/blob/master/lib/base.js#L46-L56), which means the plugin doesn't work for me.

If I run the plugin a 2nd time on the output that was generated before, then it does works. But obviously not much of a solution to always be one step behind last changes.

Can you verify if this is a real problem or something just on my machine? Are you aware of an event that's suitable for the process of reading the other outputted files and altering whats already generated?

**Comment by jamespan** [comment]
The two step inline behavior was by design, 1st compile generates the static site with remote assets inlined, 2st compile inline both remote and local assets.

I didn't find a way to do this in a one pass compile when I implement this plugin, sorry about that, but latex also need to compile three times for bibtext and links to work so I find myself an excuse.

By the way, I strongly suggest you forget about this plugin, there is some issue with some libraries like Font Awsome or web fonts, and I have stop using hexo and this plugin for months.

**Comment by JamesPan** [comment]
To inline assets, make sure you add __inline=true as query parameters to the CSS or JavaScript link
